language: rust
rust:
    - nightly
    - beta
    - stable

addons:
    apt:
        packages:
            - gcc-4.8-multilib
            - gcc-4.8-aarch64-linux-gnu
            - gcc-aarch64-linux-gnu
            - libc6-arm64-cross
            - libc6-dev-arm64-cross

matrix:
    include:
        - os: osx
          rust: stable
          env: TARGET=x86_64-apple-darwin
        - os: linux
          rust: stable
          env: TARGET=x86_64-unknown-linux-gnu
        - os: linux
          rust: stable
          env: TARGET=i686-unknown-linux-gnu
    allow_failures:
        - env: TARGET=i686-unknown-linux-gnu

before_script:
    - rustc -V
    - cargo -V
    - if [[ "${TARGET}" == "i686-unknown-linux-gnu" ]]; then rustup target add $TARGET; fi
    - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        rustup component add clippy --toolchain=nightly
        cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
      fi
    - if [[ "$TRAVIS_RUST_VERSION" != "nightly" ]]; then rustup component add clippy; fi

script:
    - if [ -n "${TARGET-}" ]; then cargo build --verbose --target $TARGET $FEATURES; fi
    - if [ -z "${TARGET}" ]; then cargo build --verbose $FEATURES; fi
    - cargo test --verbose $FEATURES --no-fail-fast
    - cargo clippy

notifications:
    email: false

before_deploy:
    - |
      if [ -n "${TARGET-}" ]; then
        cargo build --target $TARGET --release
        mkdir "pgstatprof-${TRAVIS_TAG}-${TARGET}"
        cp target/$TARGET/release/pgstatprof README.md "pgstatprof-${TRAVIS_TAG}-${TARGET}"
        zip "pgstatprof-${TRAVIS_TAG}-${TARGET}.zip" -r "pgstatprof-${TRAVIS_TAG}-${TARGET}"
      fi

deploy:
    provider: releases
    api_key:
      secure: tCuF18fHSRiyA5oDvB2kxcEP5YxejoOUF2IdKhoG3fpSvebfr3vWl8IWWuFcmFA2k/J1azlzPc3TRae2IxFQaTAiFl7woLOXHkgGoPozPhIVB2z1T9Dz6NbmzUw70o291viFgkKe9Sm9vxre1t1uBvZBAmOoXfDgR7UD93sfquHEpXynUvndDlES5ohl8ISOHAIQmeBLputIY3DaipkfNohyEXpdiNHB+jMhSILSShUHEZginKnRHMEmahruBkr8023sxFBezaAxC5WXWL1L430norY9xvIVdlXHl3y3SapeYeBkFDiaq093A+r4NRLrsnjHBSdUGJCkqVExwURomRKevYdh3rEUEq9wFIDP4CZfhy9znGgqA3A6zzO69ZUGhkugeJmVMI6KQ08pNbEm/NwY4CgUx/8rLSnUa7pWYoh8G1hG7J0RUKp8LWr+rIxtmwqqiH/hA+HsePYNPFPdhS/cILjBJ23LHfPzp4aBth1iafahSjMs5WTSzpUV0rAGZK4iKNeiR52hcYaw/jigr7LrlfVMJjDc3tVpM4JhezLhUdLe6tw1Jh/unQVOPHLYSqyFebCyIB4YX42tGbsh/MvjWrTQGYiUjzG66aKa1zv8wYYkvYeHod1ui1Sjy1bS4/SeSjF7WHt2lRoxVpan/ZWIRpMFOUwl5lIr1y02dHU=
    file: pgstatprof-${TRAVIS_TAG}-${TARGET}.zip
    cleanup: false
    on:
        repo: hhatto/pgstatprof
        tags: true
